# -*- coding: utf-8 -*-
"""MyC_AI_Task3_Printing_Positive_Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QJtxy9sDXwqL-_7xAgXD0GbKfY_RosV1
"""

start = int(input("Enter the start of range: "))
end = int(input("Enter the end of range: "))

for num in range(start, end + 1):

	if num >= 0:
		print(num, end=" ")