# -*- coding: utf-8 -*-
"""MyC_AI_Task1_Printing_HelloWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f3K8kLmEoRyDWuxzUCcJQiSkhKbQOhW6
"""

#Task1
#There we are printing "Hello World" using the print  function
print("Hello World")