# -*- coding: utf-8 -*-
"""MyC_AI_Task2_Fibonacci_Sequence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xM0C4jKDP9wAof-0BjqWavtkBI19fw4P
"""

number = int(input("How many terms? "))

n1, n2 = 0, 1
count = 0

if number <= 0:
   print("Please enter a positive integer")

elif number == 1:
   print("Fibonacci sequence upto",number,":")
   print(n1)

else:
   print("Fibonacci sequence:")
   while count < number:
       print(n1)
       nth = n1 + n2
       n1 = n2
       n2 = nth
       count += 1