# -*- coding: utf-8 -*-
"""MyCaptain_AI_Assignment_Union_Intersection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zQJ9CkVkLYEqtrnWLmemnIj_gZdIJd3x
"""

E = {0, 2, 4, 6, 8};
N = {1, 2, 3, 4, 5};

print("Union of E and N is",E | N)

print("Intersection of E and N is",E & N)

print("Difference of E and N is",E - N)

print("Symmetric difference of E and N is",E ^ N)